# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFwD5mIDjaipDKDWded2lkU0i6GwYVgu
"""

import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/train.csv.zip')  # Replace with your file path

df.head()

# Total sales by product
product_sales = df.groupby('Product Name')['Sales'].sum()
print(product_sales)

# Sales by product and region
product_region_sales = df.groupby(['Product Name', 'Region'])['Sales'].sum()
print(product_region_sales)

import matplotlib.pyplot as plt

# Plot total sales by product
product_sales.plot(kind='bar', title='Total Sales by Product', figsize=(10, 6))
plt.xlabel('Product')
plt.ylabel('Sales')
plt.tight_layout()
plt.show()